[[query]]
label = "Transactions per offset"
cypher = "MATCH (t:Transaction) RETURN t.offset AS offset, 1 AS value ORDER BY offset"

[[query]]
label = "Created per offset"
cypher = "MATCH (t:Transaction)-[:ACTION]->(c:Created) RETURN t.offset AS offset, count(c) AS value ORDER BY offset"

[[query]]
label = "Exercised per offset"
cypher = "MATCH (t:Transaction)-[:ACTION]->(e:Exercised) RETURN t.offset AS offset, count(e) AS value ORDER BY offset"
