[package]
name = "ledger-api"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
serde = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
dotenv = "0.15.0"
